version: "3.7"

services:

  nginx:
    image: nginx:1.17.2-alpine
    ports: 
      - "8080:8080"
    networks:
      - whisper
    depends_on:
      - api
      - backend
      - adminer
    volumes:
      - "./conf/nginx-default.conf:/etc/nginx/conf.d/default.conf"

  api:
    image: quay.io/yodo-io/whisper-api:6010748b
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: "9090"
      WHISPER_BACKEND_URL: http://backend:9091/
      WHISPER_AUTH_URL: http://backend:9091/
      WHISPER_JWT_ISSUER: io.yodo/whisper
      WHISPER_JWT_SECRET: eiPiequeeveixairae2u
    depends_on:
      - backend
    networks:
      - whisper

  backend:
    image: quay.io/yodo-io/whisper-backend:a8d97085
    ports:
      - "9091:9091"
    environment:
      SERVER_PORT: "9091"
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/whisper
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      WHISPER_JWT_ISSUER: io.yodo/whisper
      WHISPER_JWT_SECRET: eiPiequeeveixairae2u
    depends_on:
      - postgres # only affects startup order, no guarantee postgres is ready
    networks:
      - whisper

  postgres:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: whisper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - whisper

  adminer:
    image: adminer:4.7
    networks:
      - whisper
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./conf/adminer-login-servers.php:/var/www/html/plugins-enabled/login-servers.php"

networks:
  whisper:

volumes:
  db-data:
