version: "3.7"

services:

  nginx:
    image: nginx:1.17.2-alpine
    ports: 
      - "8080:8080"
    networks:
      - whisper
    depends_on:
      - api
      - backend
      - adminer
      - auth
    volumes:
      - "./conf/nginx-default.conf:/etc/nginx/conf.d/default.conf"

  api:
    image: quay.io/yodo-io/whisper-api:latest
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: "9090"
      WHISPER_BACKEND_URL: http://backend:9091/
      WHISPER_AUTH_URL: http://auth:9092/
    depends_on:
      - backend
    networks:
      - whisper

  backend:
    image: quay.io/yodo-io/whisper-backend:latest
    ports:
      - "9091:9091"
    environment:
      SERVER_PORT: "9091"
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/whisper_backend
      DATASOURCE_USERNAME: whisper_backend
      DATASOURCE_PASSWORD: whisper
    depends_on:
      - postgres # only affects startup order, no guarantee postgres is ready
    networks:
      - whisper

  auth:
    image: quay.io/yodo-io/whisper-auth:latest
    ports:
      - "9092:9092"
    environment:
      SERVER_PORT: "9092"
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/whisper_auth
      DATASOURCE_USERNAME: whisper_auth
      DATASOURCE_PASSWORD: whisper
    depends_on:
      - postgres # only affects startup order, no guarantee postgres is ready
    networks:
      - whisper

  postgres:
    image: postgres:9.4
    volumes:
      - "./postgres/initdb.d:/docker-entrypoint-initdb.d"
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      WHISPER_DB_PASSWORD: whisper
    networks:
      - whisper

  adminer:
    image: adminer:4.7
    networks:
      - whisper
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./conf/adminer-login-servers.php:/var/www/html/plugins-enabled/login-servers.php"

networks:
  whisper:

volumes:
  db-data:
